import React from 'react';
import { Award, TrendingUp, Sparkles, Eye } from 'lucide-react';

const ComparisonCard = ({ comparison = {} }) => {
  const { winner, engagementDiff, viewsDiff, likesRatioDiff } = comparison.metrics || {};
  const summary = comparison.summary || '';

  // Custom light parser for AI markdown text (paragraphs, titles, list items)
  const parseMarkdownSummary = (text) => {
    if (!text) return null;

    const renderFormattedText = (rawText) => {
      if (!rawText) return '';
      const parts = rawText.split('**');
      return parts.map((part, index) => {
        const cleanPart = part.replace(/\*/g, '');
        if (index % 2 === 1) {
          return (
            <strong key={index} className="font-semibold text-foreground bg-accent/25 px-1.5 py-0.5 rounded text-xs select-none">
              {cleanPart}
            </strong>
          );
        }
        return cleanPart;
      });
    };

    const lines = text.split('\n');
    return lines.map((line, idx) => {
      const trimmed = line.trim();
      if (!trimmed) return <div key={idx} className="h-2" />;

      // 1. Headings
      if (trimmed.startsWith('#')) {
        const depth = (trimmed.match(/#/g) || []).length;
        const headingContent = trimmed.replace(/#/g, '').trim().replace(/\*/g, '');
        if (depth === 1) {
          return <h2 key={idx} className="text-lg font-bold text-foreground border-b border-border/40 pb-2 mt-4 mb-2">{headingContent}</h2>;
        } else if (depth === 2) {
          return <h3 key={idx} className="text-sm font-bold text-foreground mt-4 mb-2 flex items-center gap-2">{headingContent}</h3>;
        }
        return <h4 key={idx} className="text-xs font-bold text-foreground mt-3 mb-1">{headingContent}</h4>;
      }

      // 2. List items (checked with exact bullet spaces to avoid matching bold '**' text)
      const isBulletList = trimmed.startsWith('- ') || trimmed.startsWith('* ');
      const isNumList = /^\d+\.\s+/.test(trimmed);

      if (isBulletList || isNumList) {
        let content = trimmed;
        let bulletClass = 'list-disc';
        if (isBulletList) {
          content = trimmed.slice(2).trim();
        } else {
          const numMatch = trimmed.match(/^(\d+\.)\s+(.+)$/);
          if (numMatch) {
            content = numMatch[2].trim();
            bulletClass = 'list-decimal';
          }
        }
        return (
          <li key={idx} className={`ml-6 ${bulletClass} text-sm text-muted-foreground leading-relaxed mb-2 pl-1`}>
            {renderFormattedText(content)}
          </li>
        );
      }

      // 3. Regular Paragraphs
      return (
        <p key={idx} className="text-sm text-muted-foreground leading-relaxed mb-3">
          {renderFormattedText(trimmed)}
        </p>
      );
    });
  };

  const getWinnerLabel = (w) => {
    if (w === 'youtube') return 'YouTube';
    if (w === 'instagram') return 'Instagram';
    if (w === 'tie') return 'Tie Match';
    return 'None';
  };

  return (
    <div className="w-full border border-border/80 bg-card rounded-2xl p-6 sm:p-8 shadow-lg space-y-6">
      
      {/* Header Winner Showcase */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-border/60 pb-5">
        <div className="space-y-1">
          <h3 className="text-lg font-bold tracking-tight text-foreground flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-emerald-400 shrink-0" />
            <span>AI Comparative Summary</span>
          </h3>
          <p className="text-sm text-muted-foreground">
            Core performance breakdown generated by Gemini 2.0 Flash model.
          </p>
        </div>

        {/* Winner Badge */}
        {winner && winner !== 'none' && (
          <div className="flex items-center gap-2 rounded-xl bg-emerald-500/10 border border-emerald-500/20 px-4 py-2 text-emerald-400">
            <Award className="h-5 w-5 shrink-0" />
            <div className="text-left leading-none">
              <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400/80 block">Winner</span>
              <span className="text-sm font-extrabold">{getWinnerLabel(winner)}</span>
            </div>
          </div>
        )}
      </div>

      {/* Highlights Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {/* Metric 1 */}
        <div className="border border-border/60 bg-accent/15 rounded-xl p-4 flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-400">
            <TrendingUp className="h-5 w-5 shrink-0" />
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase text-muted-foreground/80 block">Eng. Variance</span>
            <span className="text-base font-extrabold text-foreground">{engagementDiff || '0%'}</span>
          </div>
        </div>

        {/* Metric 2 */}
        <div className="border border-border/60 bg-accent/15 rounded-xl p-4 flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-red-500/10 text-red-400">
            <Eye className="h-5 w-5 shrink-0" />
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase text-muted-foreground/80 block">Views Variance</span>
            <span className="text-base font-extrabold text-foreground">
              {viewsDiff !== undefined ? (parseInt(viewsDiff) >= 0 ? `+${parseInt(viewsDiff).toLocaleString()}` : parseInt(viewsDiff).toLocaleString()) : '0'}
            </span>
          </div>
        </div>

        {/* Metric 3 */}
        <div className="border border-border/60 bg-accent/15 rounded-xl p-4 flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-purple-500/10 text-purple-400">
            <Award className="h-5 w-5 shrink-0" />
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase text-muted-foreground/80 block">Like-to-View Diff</span>
            <span className="text-base font-extrabold text-foreground">{likesRatioDiff || '0%'}</span>
          </div>
        </div>
      </div>

      {/* Main summary text box */}
      <div className="bg-accent/5 rounded-xl p-5 border border-border/60 space-y-4">
        <div className="space-y-3">
          {parseMarkdownSummary(summary)}
        </div>
      </div>

    </div>
  );
};

export default ComparisonCard;
