version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: vidiq-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: vidiq-redis
    restart: always
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    container_name: vidiq-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334" # gRPC port for Qdrant client performance
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  mongo-data:
    driver: local
  qdrant-data:
    driver: local
